baseURL = "https://mqnlbjt.github.io/hugo_blog/"
languageCode = "zh-cn"
title = "mqnlbjt"
theme = "PaperMod"
publishDir = "docs"
metaDataFormat = "yaml" # <--- 添加这一行，一劳永逸！

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  mainSections = ["posts"] # <--- 关键补充：告诉主题文章在哪里

[params.profileMode]
  enabled = true
  title = "你好，我是 mqnlbjt"
  subtitle = "这里是我的技术分享与生活点滴。欢迎来到我的数字花园！"
  imageUrl = "" # 你可以放一个头像图片的 URL
  imageWidth = 120
  imageHeight = 120

# --- 菜单配置 ---
[[menu.main]]
  identifier = "posts"
  name = "文章" # <--- 关键补充：访问文章列表的入口
  url = "/posts/"
  weight = 5

[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 20

# --- 社交链接 ---
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/mqnlbjt"
