# deploy.yml
name: Deploy Hugo site to Pages

on:
  # 在推送到`main`分支时会触发
  push:
    branches:
      - main

  # 允许你手动在 Actions 页签中执行此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以便部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过在进行中的部署之间排队的运行。
concurrency:
  group: "pages"
  cancel-in-progress: true

# 默认使用 bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.119.0 # 你可以指定你使用的 Hugo 版本
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # 拉取主题等子模块

      - name: Build with Hugo
        run: hugo --minify

      - name: Upload artifact
        # [修改点 1] 将版本从 v2 更新到 v3
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # [修改点 2] 将版本从 v3 更新到 v4
        uses: actions/deploy-pages@v4
